[
    {
        "content": "<p>For some reason, CI fails with the error<br>\n<code>./scripts/update_PR_comment.sh: No such file or directory</code><br>\nfor these three PRs:<br>\n<a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/9465178854\">https://github.com/leanprover-community/mathlib4/actions/runs/9465178854</a><br>\n<a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/9465906261\">https://github.com/leanprover-community/mathlib4/actions/runs/9465906261</a><br>\n<a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/9466395834\">https://github.com/leanprover-community/mathlib4/actions/runs/9466395834</a></p>",
        "id": 444019416,
        "sender_full_name": "Vasily Nesterov",
        "timestamp": 1718116803
    },
    {
        "content": "<p>cc <span class=\"user-mention\" data-user-id=\"321459\">@Damiano Testa</span></p>",
        "id": 444019493,
        "sender_full_name": "YaÃ«l Dillies",
        "timestamp": 1718116837
    },
    {
        "content": "<p>This is strange: the PR has a <code>PR summary</code> comment, but the CI step for it appears to be missing in <code>.github/workflow</code>.  Could you try to merge current master into it and see if the file <code>.github/workflows/PR_summary.yml</code> appears?</p>",
        "id": 444020688,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1718117168
    },
    {
        "content": "<p>I suspect that this PR managed to get an intermediate version of the <code>PR_summary</code> script to work, but then missed the update that would make it correct the issue that it is seeing now.</p>",
        "id": 444021132,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1718117302
    },
    {
        "content": "<p>I merged master into my branch (locally). <code>.github/workflows/PR_summary.yml</code> is here.</p>",
        "id": 444025976,
        "sender_full_name": "Vasily Nesterov",
        "timestamp": 1718118604
    },
    {
        "content": "<p>Ok, that is a good sign.  I think that either pushing as is might work, or maybe rebase master first.</p>",
        "id": 444026161,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1718118650
    },
    {
        "content": "<p>The issue could be that the script would still git-travel backwards in time to a version of master that does not have the scripts that master contains now and the script does not know what to do in that case.</p>\n<p>Rebasing may help the script use a more recent version of master instead.</p>",
        "id": 444026319,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1718118702
    },
    {
        "content": "<p>But, simply pushing what you currently have may be enough, assuming that the algorithm that git uses to find a common ancestor uses a recent-enough version of master.</p>",
        "id": 444026582,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1718118758
    },
    {
        "content": "<p>I created <a href=\"https://github.com/leanprover-community/mathlib4/pull/13728\">#13728</a> (and I also already closed it) to check that simply merging master and pushing solves the CI error related to <code>PR summary</code>.</p>",
        "id": 444034130,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1718120238
    }
]