[
    {
        "content": "<p>I am getting the above error message when trying to invoke simp on a large goal. Is there some argument I can pass in to get this message to go away?</p>",
        "id": 420581625,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1707449773
    },
    {
        "content": "<p>The maxSteps in <a href=\"https://leanprover-community.github.io/mathlib4_docs/find/?pattern=Lean.Meta.Simp.Config#doc\">docs#Lean.Meta.Simp.Config</a> I guess. It might be nice to make the error message communicate this</p>",
        "id": 420581994,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1707450176
    },
    {
        "content": "<p>Ok here's <a href=\"https://github.com/leanprover/lean4/pull/3287\">lean4#3287</a>.</p>",
        "id": 420583365,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1707451387
    }
]