[
    {
        "content": "<p>I just got the following error when opening a project in vscode:</p>\n<div class=\"codehilite\" data-code-language=\"Text only\"><pre><span></span><code>Internal error (while activating Lean 4 features):\n\nError: command 'lean4.restartFile' already exists\n    at h.registerCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199082)\n    at Object.registerCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:21945)\n    at new t.LeanClientProvider (/home/adam/.vscode/extensions/leanprover.lean4-0.0.167/dist/extension.js:1:257630)\n    at /home/adam/.vscode/extensions/leanprover.lean4-0.0.167/dist/extension.js:1:192866\n    at Generator.next (&lt;anonymous&gt;)\n    at s (/home/adam/.vscode/extensions/leanprover.lean4-0.0.167/dist/extension.js:1:191621)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n</code></pre></div>\n<p>Things seem to be working okay for now, but the error is a bit concerning. I don't really know whether this is something I should actually worry about.</p>",
        "id": 446135693,
        "sender_full_name": "Adam Topaz",
        "timestamp": 1718991341
    },
    {
        "content": "<p>Thanks, I'll look into it. 0.0.167 now makes activation errors explicit and displays them so that we find out about them and fix them. This is probably an issue that already existed before and it is only now being made visible.</p>",
        "id": 446142483,
        "sender_full_name": "Marc Huisinga",
        "timestamp": 1718993705
    },
    {
        "content": "<p>I may have found the race condition that could cause this issue. A fix for it is in 0.0.168. Please let me know if you still encounter the internal error on that version.</p>",
        "id": 446163649,
        "sender_full_name": "Marc Huisinga",
        "timestamp": 1719000656
    }
]