[
    {
        "content": "<p>I accidentally wrote <code>import Foo</code> in <code>Foo.lean</code> in <a href=\"https://github.com/leanprover-community/mathlib4/pull/11725\">#11725</a> (for <code>Foo = Mathlib.Algebra.BigOperators.List.Order</code>) and the getting cache step instantly overflowed: <a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/8470947044/job/23209945412?pr=11725\">https://github.com/leanprover-community/mathlib4/actions/runs/8470947044/job/23209945412?pr=11725</a></p>",
        "id": 430122846,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1711645647
    },
    {
        "content": "<p>Can we have better failure behavior?</p>",
        "id": 430122888,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1711645661
    },
    {
        "content": "<p>I just made this same mistake, I would also like better behavior here.</p>",
        "id": 430684807,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1712017110
    }
]